algoritmo "semnome"
// Função :
// Autor :
// Data : 23/08/2022
// Seção de Declarações 
var
contador,numero,soma,qntd:inteiro
media:real
inicio
// Seção de Comandos
para contador de 1 ate 5 faca
     escreval("Digite um numero:")
     leia(numero)
     se (numero mod 2 =0) entao
      soma <- soma+numero
      qntd <- qntd + 1
fimse
fimpara

escreval("a soma é",soma)
escreval("Achei",qntd," pares")
//media <- soma/5
//escreval("a média é",media)

fimalgoritmo
