algoritmo "semnome"
// Função :achar pares
// Autor :Fellipe M.
// Data : 23/08/2022
// Seção de Declarações
var
contador,numero,soma,qntd:inteiro
media:real
inicio
// Seção de Comandos
para contador de 1 ate 500 faca
     se (contador mod 2 =0) entao
      soma <- soma+contador
      qntd <- qntd + 1
fimse
fimpara

escreval("a soma é",soma)
escreval("Achei",qntd," pares")
media <- soma/250
escreval("a média é",media)

fimalgoritmo

