algoritmo "numero par ou impar"
// Função : Verificar se o numero é par ou impar
// Autor : Fellipe M.
// Data : 02/08/2022
// Seção de Declarações 
var
numero:inteiro
inicio
// Seção de Comandos
escreval("Digite um número:")
leia(numero)

se numero mod 2=0 entao
 escreval("o número que você escreveu é",numero," e ele é par")
senao
 escreval("o número que você escreveu é",numero," e ele é ímpar")
fimse
fimalgoritmo

