algoritmo "Média"
// Função :Calcular média de 10 alunos
// Autor :Fellipe M.
// Data : 20/09/2022
// Seção de Declarações 
var
n1,n2,numfinal:inteiro
media:real
inicio
repita
      escreval("Digite um número:")
      leia(n1)
      escreval("Digite um número:")
      leia(n2)
      media<- (n1+n2)/2
      escreval("a média é",media)
      numfinal <- numfinal+1
ate (numfinal = 10)
fimalgoritmo
