algoritmo "Calcularmedia"
// Função :  Calcular a média de 2 notas
// Autor :   Fellipe M.
// Data : 26/04/2022
// Seção de Declarações 
var
   p1,p2,media:real
inicio
// Dados de Entrada

escreval("Digite a nota da sua p1:")
leia (p1)
escreval("Digite a nota da sua p2:")
leia(p2)
//Fim dos dados

//Processamento
media <- (p1+p2)/2
//Fim do Processamento

//Dados de Saída
escreval("A Média de suas notas é de:",media)
//Fim dos Dados de Saída

fimalgoritmo
